Código/GestorDocumentosEntrada/GestorDocumentosEntrada/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestorDocumentosEntrada.Controllers
{
    public class MenuController : Controller
    {
        // GET: Menu
        public ActionResult platFormMenu()
        {
            return View();
        }

        public ActionResult platFormBossMenu()
        {
            return View();
        }

        public ActionResult administrativeMenu()
        {
            return View();
        }

        public ActionResult administratorMenu()
        {
            return View();
        }
    }
}

Código/GestorDocumentosEntrada/GestorDocumentosEntrada/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GestorDocumentosEntrada.Models;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.Data;

namespace GestorDocumentosEntrada.Controllers
{
    public class ReportsController : Controller
    {
        private ProcedureConnection con = new ProcedureConnection();

        public ActionResult Statistic()
        {
            ViewBag.deparmentTable = con.getDepartments();
            ViewBag.platformersTable = con.getPlatformers();
            return View();
        }

        public ActionResult Binnacle()
        {
            return View();
        }

        public ActionResult getBinnacle(DateTime from, DateTime to)
        {
            ViewBag.searchTable = con.getBinnacle(from, to);
            return PartialView();
        }

        public String createBinnaclePDF(DateTime date1, DateTime date2)
        {
            DataSet binnacleToExport = con.getBinnacle(date1, date2);

            if (binnacleToExport.Tables["Table"].Rows.Count != 0)
            {
                // Creamos el documento con el tamaño de página tradicional
                Document doc = new Document(PageSize.LETTER);
                // Indicamos donde vamos a guardar el documento
                String pdfName = "Bitacora_" + date1.ToString("dd-MM-yyyy") + "_" + date2.ToString("dd-MM-yyyy");
                PdfWriter writer = PdfWriter.GetInstance(doc,
                                            new FileStream(@"C:\Users\ProyectoVerano_2016\Downloads\"+pdfName+".pdf", FileMode.Create));

             

                // Le colocamos el título y el autor
                // **Nota: Esto no será visible en el documento
                doc.AddTitle("Bitacora");
                doc.AddCreator("Gestor de Entrada de Documentos");

                // Abrimos el archivo
                doc.Open();

                // Creamos el tipo de Font que vamos utilizar
                iTextSharp.text.Font tableFont = new iTextSharp.text.Font(iTextSharp.text.Font.FontFamily.HELVETICA, 10, iTextSharp.text.Font.NORMAL, BaseColor.BLACK);

                BaseFont headerBaseFont = BaseFont.CreateFont(BaseFont.TIMES_BOLD, BaseFont.CP1252, false);
                Font headerFont = new Font(headerBaseFont, 12, Font.BOLD, iTextSharp.text.BaseColor.GRAY);

                BaseFont titleBaseFont = BaseFont.CreateFont(BaseFont.TIMES_BOLD, BaseFont.CP1252, false);
                Font titleFont = new Font(titleBaseFont, 16, Font.BOLD, iTextSharp.text.BaseColor.BLACK);

                BaseFont dateBaseFont = BaseFont.CreateFont(BaseFont.TIMES_BOLD, BaseFont.CP1252, false);
                Font dateFont = new Font(dateBaseFont, 12, Font.NORMAL, iTextSharp.text.BaseColor.BLACK);
               
                // Escribimos el encabezamiento en el documento
                Paragraph programName = new Paragraph("Gestor de Entrada de Documentos", headerFont);
                programName.Alignment = Element.ALIGN_LEFT;
                doc.Add(programName);
                Paragraph placeName = new Paragraph("Municipalidad de Alajuelita", headerFont);
                placeName.Alignment = Element.ALIGN_LEFT;
                doc.Add(placeName);
                doc.Add(Chunk.NEWLINE);

                Paragraph title = new Paragraph("Bitácora de Ingreso de Documentos", titleFont);
                title.Alignment = Element.ALIGN_CENTER;
                doc.Add(title);
                doc.Add(Chunk.NEWLINE);

                String text = "Bitácora generada a partir del ingreso de documentos en el período comprendido entre el " + date1.ToShortDateString()
                    + " al " + date2.ToShortDateString() + ", obtenido el día " + DateTime.Now.ToShortDateString() + " a las " 
                    + DateTime.Now.ToString("HH:mm");
                Paragraph dateFrom = new Paragraph(text, dateFont);
                dateFrom.Alignment = Element.ALIGN_LEFT;
                doc.Add(dateFrom);
                doc.Add(Chunk.NEWLINE);

                // Creamos una tabla que contendrá el nombre, apellido y país
                // de nuestros visitante.
                PdfPTable tblPrueba = new PdfPTable(7);
                tblPrueba.WidthPercentage = 100;

                // Configuramos el título de las columnas de la tabla
                PdfPCell clDate = new PdfPCell(new Phrase("Fecha", tableFont));
                clDate.BorderWidth = 0;
                clDate.BorderWidthBottom = 0.75f;

                PdfPCell clConsecutive = new PdfPCell(new Phrase("Consecutivo", tableFont));
                clConsecutive.BorderWidth = 0;
                clConsecutive.BorderWidthBottom = 0.75f;

                PdfPCell clDepartment = new PdfPCell(new Phrase("Departamento", tableFont));
                clDepartment.BorderWidth = 0;
                clDepartment.BorderWidthBottom = 0.75f;

                PdfPCell clId = new PdfPCell(new Phrase("Cédula", tableFont));
                clId.BorderWidth = 0;
                clId.BorderWidthBottom = 0.75f;

                PdfPCell clProcedureState = new PdfPCell(new Phrase("Estado del Trámite", tableFont));
                clProcedureState.BorderWidth = 0;
                clProcedureState.BorderWidthBottom = 0.75f;

                PdfPCell clProcedureType = new PdfPCell(new Phrase("Tipo de Trámite", tableFont));
                clProcedureType.BorderWidth = 0;
                clProcedureType.BorderWidthBottom = 0.75f;

                PdfPCell clPlatformist = new PdfPCell(new Phrase("Plataformista", tableFont));
                clPlatformist.BorderWidth = 0;
                clPlatformist.BorderWidthBottom = 0.75f;

                // Añadimos las celdas a la tabla
                tblPrueba.AddCell(clDate);
                tblPrueba.AddCell(clConsecutive);
                tblPrueba.AddCell(clDepartment);
                tblPrueba.AddCell(clId);
                tblPrueba.AddCell(clProcedureState);
                tblPrueba.AddCell(clProcedureType);
                tblPrueba.AddCell(clPlatformist);


                foreach (DataRow row in binnacleToExport.Tables["Table"].Rows)
                {
                    // Llenamos la tabla con información
                    clDate = new PdfPCell(new Phrase((DateTime.Parse(row["Fecha"].ToString()).ToShortDateString()), tableFont));
                    clDate.BorderWidth = 0;

                    clConsecutive = new PdfPCell(new Phrase((row["Consecutivo"]).ToString(), tableFont));
                    clConsecutive.BorderWidth = 0;

                    clDepartment = new PdfPCell(new Phrase((row["Departamento"]).ToString(), tableFont));
                    clDepartment.BorderWidth = 0;

                    clId = new PdfPCell(new Phrase((row["Cèdula"]).ToString(), tableFont));
                    clId.BorderWidth = 0;

                    clProcedureState = new PdfPCell(new Phrase((row["Estado"]).ToString(), tableFont));
                    clProcedureState.BorderWidth = 0;

                    clProcedureType = new PdfPCell(new Phrase((row["Tipo de Procedimiento"]).ToString(), tableFont));
                    clProcedureType.BorderWidth = 0;

                    clPlatformist = new PdfPCell(new Phrase((row["Plataformista"]).ToString(), tableFont));
                    clPlatformist.BorderWidth = 0;

                    // Añadimos las celdas a la tabla
                    tblPrueba.AddCell(clDate);
                    tblPrueba.AddCell(clConsecutive);
                    tblPrueba.AddCell(clDepartment);
                    tblPrueba.AddCell(clId);
                    tblPrueba.AddCell(clProcedureState);
                    tblPrueba.AddCell(clProcedureType);
                    tblPrueba.AddCell(clPlatformist);
                }

                // Finalmente, añadimos la tabla al documento PDF y cerramos el documento
                doc.Add(tblPrueba);

                doc.Close();
                writer.Close();

                return "yes";
            }
            else {
                return "no";
            }
            
        }

        public String createStatisticByDatePDF(String urlDepartment, String urlPlatform, DateTime date1, DateTime date2)
        {
                // Creamos el documento con el tamaño de página tradicional
                Document doc = new Document(PageSize.LETTER);
                // Indicamos donde vamos a guardar el documento
                String pdfName = "Estadisticas_" + date1.ToString("dd-MM-yyyy") + "_" + date2.ToString("dd-MM-yyyy");
                PdfWriter writer = PdfWriter.GetInstance(doc,
                                            new FileStream(@"C:\Users\ProyectoVerano_2016\Downloads\" + pdfName + ".pdf", FileMode.Create));



                // Le colocamos el título y el autor
                // **Nota: Esto no será visible en el documento
                doc.AddTitle("Estadisticas por Fecha");
                doc.AddCreator("Gestor de Entrada de Documentos");

                // Abrimos el archivo
                doc.Open();

                // Creamos el tipo de Font que vamos utilizar
                BaseFont headerBaseFont = BaseFont.CreateFont(BaseFont.TIMES_BOLD, BaseFont.CP1252, false);
                Font headerFont = new Font(headerBaseFont, 12, Font.BOLD, iTextSharp.text.BaseColor.GRAY);

                BaseFont titleBaseFont = BaseFont.CreateFont(BaseFont.TIMES_BOLD, BaseFont.CP1252, false);
                Font titleFont = new Font(titleBaseFont, 16, Font.BOLD, iTextSharp.text.BaseColor.BLACK);

                BaseFont dateBaseFont = BaseFont.CreateFont(BaseFont.TIMES_BOLD, BaseFont.CP1252, false);
                Font dateFont = new Font(dateBaseFont, 12, Font.NORMAL, iTextSharp.text.BaseColor.BLACK);

                // Escribimos el encabezamiento en el documento
                Paragraph programName = new Paragraph("Gestor de Entrada de Documentos", headerFont);

Código/GestorDocumentosEntrada/GestorDocumentosEntrada/Views/Reports/Binnacle.cshtml
@{
    ViewBag.Title = "Bitacora";
}

<div class="searchProcedure">
    <div class="row col-sm-12">
        <div class="col-sm-2">
            <img class="menuHeaderImage" src="@Url.Content("~/Content/Image/escudoSinFondo.png")">
        </div>
        <div class="col-sm-10">
            <h3 class="headerSearchTitle">Generar Bitácora</h3>
        </div>
    </div>

    <div class="searchDivContainer row col-sm-12" id="divDate">
        <div class="labelSearchDiv col-sm-1">
            <label class="labelSearch">de</label>
        </div>
        <div class="col-sm-3">
            <input type="date" class="form-control" id="dateBegin">
        </div>
        <div class="labelSearchDiv col-sm-1">
            <label class="labelSearch">al</label>
        </div>
        <div class="col-sm-3">
            <input type="date" class="form-control" id="dateEnd">
        </div>
        <div class="col-sm-3">
            <button class="btnSearch" id="searchDate">Buscar</button>
        </div>
    </div>

    <div class="searchDivContainer row col-sm-12">
        <div class="col-sm-12" id="tbl">

        </div>
    </div>
    <div class="searchDivContainer row col-sm-12" >
        <div class="col-sm-6">
            <button type="button" class="sendButton" onClick="location.href='@Url.Action("platFormBossMenu", "Menu")'">Regresar</button>
        </div>
        <div class="col-sm-6 btnExportContainer" id="btnExportPDFContainer">
            <button type="button" class="sendButton" id="exportPDF">Guardar PDF</button>
        </div>
    </div>
</div>

<div id="errorModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" id="modalTittle"></h4>
      </div>
      <div class="modal-body">
        <label id="textMessage"></label>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>


@section Scripts {
<script>

    var from;
    var to;
    $('#searchDate').click(function () {
        var dateBegin = $('#dateBegin').val();
        var dateEnd = $('#dateEnd').val();
        if (dateBegin == '' || dateEnd == '') {
            document.getElementById('modalTittle').innerHTML = 'Error';
            document.getElementById('textMessage').innerHTML = 'Ingrese la fecha en ambos espacios';
            $('#errorModal').modal('toggle');
        }
        else {
            if (dateBegin.replace('-', '/') > dateEnd.replace('-', '/')) {
                document.getElementById('modalTittle').innerHTML = 'Error';
                document.getElementById('textMessage').innerHTML = 'El primer espacio de fecha debe de ser menor que el segundo';
                $('#errorModal').modal('toggle');
            }
            if (dateBegin.replace('-', '/') <= dateEnd.replace('-', '/')) {
                from = dateBegin;
                to = dateEnd;
                $('#tbl').load('/Reports/getBinnacle', { from: dateBegin, to: dateEnd })
                .error(function (xhr, status) {
                    alert(status);
                })
            }
        }
    });

    $('#exportPDF').click(function () {
        if (from != null && to != null) {
            $.ajax({
                url: '/Reports/createBinnaclePDF',
                contentType: 'application/html; charset=utf-8',
                data: { date1: from, date2: to },
                type: 'GET',
                dataType: 'text'

            })
            .success(function (result) {
                console.log(result);
                if (result == 'yes') {
                    document.getElementById('modalTittle').innerHTML = 'Éxito';
                    document.getElementById('textMessage').innerHTML = 'Archivo guardado como PDF';
                    $('#errorModal').modal('toggle');
                }
                else {
                    document.getElementById('modalTittle').innerHTML = 'Error';
                    document.getElementById('textMessage').innerHTML = 'No hay datos disponibles para exportar';
                    $('#errorModal').modal('toggle');
                }

            })
            .error(function (xhr, status) {
                alert(status);
            })
        } else {
            document.getElementById('modalTittle').innerHTML = 'Error';
            document.getElementById('textMessage').innerHTML = 'No hay datos disponibles para exportar';
            $('#errorModal').modal('toggle');
        }
      
    });
</script>
    }

Código/GestorDocumentosEntrada/GestorDocumentosEntrada/Views/Reports/getBinnacle.cshtml
@using System.Data;
@{ Layout = null;}

<div class="row col-md-12">
    @if (ViewBag.searchTable.Tables["Table"].Rows.Count != 0)
    {
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Fecha</th>
                    <th>Consecutivo</th>
                    <th>Departamento</th>
                    <th>Cédula</th>
                    <th>Estado del Trámite</th>
                    <th>Tipo de Trámite</th>
                    <th>Plataformista</th>
                </tr>
            </thead>
            <tbody>
                @foreach (DataRow row in ViewBag.searchTable.Tables["Table"].Rows)
                { 
                    <tr>
                        <td>@(DateTime.Parse(row["Fecha"].ToString()).ToShortDateString())</td>
                        <td>@row["Consecutivo"]</td> 
                        <td>@row["Departamento"]</td> 
                        <td>@row["Cèdula"]</td>
                        <td>@row["Estado"]</td> 
                        <td>@row["Tipo de Procedimiento"]</td> 
                        <td>@row["Plataformista"]</td> 
                    </tr>
                }
            </tbody>
        </table>
    }else {
        <div class="alert alert-dismissible alert-info">
          <label>No se encontraron trámites registrados en el período consultado</label>
        </div>
    }
</div>