Código/GestorDocumentosEntrada/GestorDocumentosEntrada/Controllers/LogInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GestorDocumentosEntrada.Models;
using System.Globalization;

namespace GestorDocumentosEntrada.Controllers
{
    public class LogInController : Controller
    {
        //
        // GET: /LogIn/
        private ProcedureConnection con = new ProcedureConnection();
        /**/
        public ActionResult Index()
        {
            Session.Abandon();
            return View();
        }
        /**/
        [HttpPost]
        public ActionResult Index(FormCollection form)
        {
            String email = form["email"];
            String pwd = form["pwd"];
            int generalExist = con.getIDLogin(email, pwd); // Buscamos si el usuario realmente existe
            int idTablePlat = 0;
            if (generalExist == 0)  // Si el resultado de la busqueda es 0, ese email con esa contraseña NO existen
            {
                ViewBag.messege = "Lo sentimos, el correo y la contraseña no coinciden";
                return View();
            }
            else if (generalExist == -1) // Si el resultado es -1 hubo un problema de conexion
            {
                ViewBag.messege = "Lo sentimos, Hubo un error de conexiòn";
                return View();
            }
            else if (generalExist != 0 && generalExist != -1) // Si es cualquier otro numero, serìa el ID de la tabla login por lo que el usuario existe
            {
                idTablePlat = con.getIDPlatformer(generalExist); // Busca si es plataformista
                if (idTablePlat != 0 && idTablePlat != -1) // Si es plataformista
                {
                    int auxID = con.IsABoss(idTablePlat); // Busca si es el jefe de plataforma
                    if (auxID == 0) // Es jefe de plataforma
                    {
                        Session["userName"] = con.getNamePlatformer(idTablePlat);
                        Session["platfomerID"] = idTablePlat;
                        Session["isABoss"] = 0;
                        return RedirectToAction("platFormMenu", "Menu");
                    }
                    else // No es jefe de plataforma
                    {
                        Session["userName"] = con.getNamePlatformer(idTablePlat);
                        Session["platfomerID"] = idTablePlat;
                        Session["isABoss"] = 1;
                        return RedirectToAction("platFormBossMenu", "Menu");
                    }
                }
                else // No es plataformista
                { 
                    int idTableSec = con.getIDSecretary(generalExist);
                    
                    if (idTableSec != 0 && idTableSec != -1)
                    {
                        String name = con.getNameSecretary(idTableSec);
                        int idDep = con.getIDDepartmentBySec(idTableSec);
                        String depName = con.getNameDep(idDep);
                        if (depName.CompareTo("INFORMÁTICA") == 0 || depName.CompareTo("Informática") == 0)
                        {
                            Session["userName"] = name;
                            Session["ID"] = idTableSec;
                            Session["idDepartment"] = idDep;
                            Session["isAdministrator"] = 1;
                            return RedirectToAction("administratorMenu", "Menu");
                        }
                        else
                        {
                            Session["userName"] = name;
                            Session["ID"] = idTableSec;
                            Session["idDepartment"] = idDep;
                            Session["isAdministrator"] = 0;
                            return RedirectToAction("administrativeMenu", "Menu");
                        }
                    }
                    else 
                    {
                            ViewBag.messege = "Lo sentimos, Hubo un error";
                            return View();
                        
                    } 
                    
                }
            }

           
            return View();
        }
        
        
    }
}

Código/GestorDocumentosEntrada/GestorDocumentosEntrada/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestorDocumentosEntrada.Controllers
{
    public class MenuController : Controller
    {
        // GET: Menu
        public ActionResult platFormMenu()
        {
            return View();
        }

        public ActionResult platFormBossMenu()
        {
            return View();
        }

        public ActionResult administrativeMenu()
        {
            return View();
        }

        public ActionResult administratorMenu()
        {
            return View();
        }
    }
}

Código/GestorDocumentosEntrada/GestorDocumentosEntrada/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GestorDocumentosEntrada.Models;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.Data;

namespace GestorDocumentosEntrada.Controllers
{
    public class ReportsController : Controller
    {
        private ProcedureConnection con = new ProcedureConnection();

        public ActionResult Statistic()
        {
            ViewBag.deparmentTable = con.getDepartments();
            ViewBag.platformersTable = con.getPlatformers();
            return View();
        }

        public ActionResult Binnacle()
        {
            return View();
        }

        public ActionResult getBinnacle(DateTime from, DateTime to)
        {
            ViewBag.searchTable = con.getBinnacle(from, to);
            return PartialView();
        }

        public String createBinnaclePDF(DateTime date1, DateTime date2)
        {
            DataSet binnacleToExport = con.getBinnacle(date1, date2);

            if (binnacleToExport.Tables["Table"].Rows.Count != 0)
            {
                // Creamos el documento con el tamaño de página tradicional
                Document doc = new Document(PageSize.LETTER);
                // Indicamos donde vamos a guardar el documento
                String pdfName = "Bitacora_" + date1.ToString("dd-MM-yyyy") + "_" + date2.ToString("dd-MM-yyyy");
                PdfWriter writer = PdfWriter.GetInstance(doc,
                                            new FileStream(@"C:\Users\ProyectoVerano_2016\Downloads\"+pdfName+".pdf", FileMode.Create));

             

                // Le colocamos el título y el autor
                // **Nota: Esto no será visible en el documento
                doc.AddTitle("Bitacora");
                doc.AddCreator("Gestor de Entrada de Documentos");

                // Abrimos el archivo
                doc.Open();

                // Creamos el tipo de Font que vamos utilizar
                iTextSharp.text.Font tableFont = new iTextSharp.text.Font(iTextSharp.text.Font.FontFamily.HELVETICA, 10, iTextSharp.text.Font.NORMAL, BaseColor.BLACK);

                BaseFont headerBaseFont = BaseFont.CreateFont(BaseFont.TIMES_BOLD, BaseFont.CP1252, false);
                Font headerFont = new Font(headerBaseFont, 12, Font.BOLD, iTextSharp.text.BaseColor.GRAY);

                BaseFont titleBaseFont = BaseFont.CreateFont(BaseFont.TIMES_BOLD, BaseFont.CP1252, false);
                Font titleFont = new Font(titleBaseFont, 16, Font.BOLD, iTextSharp.text.BaseColor.BLACK);

                BaseFont dateBaseFont = BaseFont.CreateFont(BaseFont.TIMES_BOLD, BaseFont.CP1252, false);
                Font dateFont = new Font(dateBaseFont, 12, Font.NORMAL, iTextSharp.text.BaseColor.BLACK);
               
                // Escribimos el encabezamiento en el documento
                Paragraph programName = new Paragraph("Gestor de Entrada de Documentos", headerFont);
                programName.Alignment = Element.ALIGN_LEFT;
                doc.Add(programName);
                Paragraph placeName = new Paragraph("Municipalidad de Alajuelita", headerFont);
                placeName.Alignment = Element.ALIGN_LEFT;
                doc.Add(placeName);
                doc.Add(Chunk.NEWLINE);

                Paragraph title = new Paragraph("Bitácora de Ingreso de Documentos", titleFont);
                title.Alignment = Element.ALIGN_CENTER;
                doc.Add(title);
                doc.Add(Chunk.NEWLINE);

                String text = "Bitácora generada a partir del ingreso de documentos en el período comprendido entre el " + date1.ToShortDateString()
                    + " al " + date2.ToShortDateString() + ", obtenido el día " + DateTime.Now.ToShortDateString() + " a las " 
                    + DateTime.Now.ToString("HH:mm");
                Paragraph dateFrom = new Paragraph(text, dateFont);
                dateFrom.Alignment = Element.ALIGN_LEFT;
                doc.Add(dateFrom);
                doc.Add(Chunk.NEWLINE);

                // Creamos una tabla que contendrá el nombre, apellido y país
                // de nuestros visitante.
                PdfPTable tblPrueba = new PdfPTable(7);
                tblPrueba.WidthPercentage = 100;

                // Configuramos el título de las columnas de la tabla
                PdfPCell clDate = new PdfPCell(new Phrase("Fecha", tableFont));
                clDate.BorderWidth = 0;
                clDate.BorderWidthBottom = 0.75f;

                PdfPCell clConsecutive = new PdfPCell(new Phrase("Consecutivo", tableFont));
                clConsecutive.BorderWidth = 0;
                clConsecutive.BorderWidthBottom = 0.75f;

                PdfPCell clDepartment = new PdfPCell(new Phrase("Departamento", tableFont));
                clDepartment.BorderWidth = 0;
                clDepartment.BorderWidthBottom = 0.75f;

                PdfPCell clId = new PdfPCell(new Phrase("Cédula", tableFont));
                clId.BorderWidth = 0;
                clId.BorderWidthBottom = 0.75f;

                PdfPCell clProcedureState = new PdfPCell(new Phrase("Estado del Trámite", tableFont));
                clProcedureState.BorderWidth = 0;
                clProcedureState.BorderWidthBottom = 0.75f;

                PdfPCell clProcedureType = new PdfPCell(new Phrase("Tipo de Trámite", tableFont));
                clProcedureType.BorderWidth = 0;
                clProcedureType.BorderWidthBottom = 0.75f;

                PdfPCell clPlatformist = new PdfPCell(new Phrase("Plataformista", tableFont));
                clPlatformist.BorderWidth = 0;
                clPlatformist.BorderWidthBottom = 0.75f;

                // Añadimos las celdas a la tabla
                tblPrueba.AddCell(clDate);
                tblPrueba.AddCell(clConsecutive);
                tblPrueba.AddCell(clDepartment);
                tblPrueba.AddCell(clId);
                tblPrueba.AddCell(clProcedureState);
                tblPrueba.AddCell(clProcedureType);
                tblPrueba.AddCell(clPlatformist);


                foreach (DataRow row in binnacleToExport.Tables["Table"].Rows)
                {
                    // Llenamos la tabla con información
                    clDate = new PdfPCell(new Phrase((DateTime.Parse(row["Fecha"].ToString()).ToShortDateString()), tableFont));
                    clDate.BorderWidth = 0;

                    clConsecutive = new PdfPCell(new Phrase((row["Consecutivo"]).ToString(), tableFont));
                    clConsecutive.BorderWidth = 0;

                    clDepartment = new PdfPCell(new Phrase((row["Departamento"]).ToString(), tableFont));
                    clDepartment.BorderWidth = 0;

                    clId = new PdfPCell(new Phrase((row["Cèdula"]).ToString(), tableFont));
                    clId.BorderWidth = 0;

                    clProcedureState = new PdfPCell(new Phrase((row["Estado"]).ToString(), tableFont));
                    clProcedureState.BorderWidth = 0;

                    clProcedureType = new PdfPCell(new Phrase((row["Tipo de Procedimiento"]).ToString(), tableFont));
                    clProcedureType.BorderWidth = 0;

                    clPlatformist = new PdfPCell(new Phrase((row["Plataformista"]).ToString(), tableFont));
                    clPlatformist.BorderWidth = 0;

                    // Añadimos las celdas a la tabla
                    tblPrueba.AddCell(clDate);
                    tblPrueba.AddCell(clConsecutive);
                    tblPrueba.AddCell(clDepartment);
                    tblPrueba.AddCell(clId);
                    tblPrueba.AddCell(clProcedureState);
                    tblPrueba.AddCell(clProcedureType);
                    tblPrueba.AddCell(clPlatformist);
                }

                // Finalmente, añadimos la tabla al documento PDF y cerramos el documento
                doc.Add(tblPrueba);

                doc.Close();
                writer.Close();

                return "yes";
            }
            else {
                return "no";
            }
            
        }

        public String createStatisticByDatePDF(String urlDepartment, String urlPlatform, DateTime date1, DateTime date2)
        {
                // Creamos el documento con el tamaño de página tradicional
                Document doc = new Document(PageSize.LETTER);
                // Indicamos donde vamos a guardar el documento
                String pdfName = "Estadisticas_" + date1.ToString("dd-MM-yyyy") + "_" + date2.ToString("dd-MM-yyyy");
                PdfWriter writer = PdfWriter.GetInstance(doc,
                                            new FileStream(@"C:\Users\ProyectoVerano_2016\Downloads\" + pdfName + ".pdf", FileMode.Create));



                // Le colocamos el título y el autor
                // **Nota: Esto no será visible en el documento
                doc.AddTitle("Estadisticas por Fecha");
                doc.AddCreator("Gestor de Entrada de Documentos");

                // Abrimos el archivo
                doc.Open();

                // Creamos el tipo de Font que vamos utilizar
                BaseFont headerBaseFont = BaseFont.CreateFont(BaseFont.TIMES_BOLD, BaseFont.CP1252, false);
                Font headerFont = new Font(headerBaseFont, 12, Font.BOLD, iTextSharp.text.BaseColor.GRAY);

                BaseFont titleBaseFont = BaseFont.CreateFont(BaseFont.TIMES_BOLD, BaseFont.CP1252, false);
                Font titleFont = new Font(titleBaseFont, 16, Font.BOLD, iTextSharp.text.BaseColor.BLACK);

                BaseFont dateBaseFont = BaseFont.CreateFont(BaseFont.TIMES_BOLD, BaseFont.CP1252, false);
                Font dateFont = new Font(dateBaseFont, 12, Font.NORMAL, iTextSharp.text.BaseColor.BLACK);

                // Escribimos el encabezamiento en el documento
                Paragraph programName = new Paragraph("Gestor de Entrada de Documentos", headerFont);

Código/GestorDocumentosEntrada/GestorDocumentosEntrada/Views/Menu/administrativeMenu.cshtml
@{
    ViewBag.Title = "Menu Principal";
}

<div class="menu">
    <div class="row col-sm-8">
        <div class="col-sm-3">
            <img class="menuHeaderImage" src="@Url.Content("~/Content/Image/escudoSinFondo.png")">
        </div>
        <div class="col-sm-9">
            <h3 class="menuHeaderTitle">Menú Principal</h3>
        </div>
    </div>
    <div class="row col-sm-8">
        <div class="col-sm-12">
            <button type="button" class="menuButton" onClick="location.href='@Url.Action("dailyProcedure", "Procedure")'">Recibir Documentos Diarios</button>
            <button type="button" class="menuButton" onClick="location.href='@Url.Action("displayProcedure", "Procedure")'">Vizualizar Trámite</button>
            <button type="button" class="menuButton" onClick="location.href='@Url.Action("Index", "LogIn")'">Salir</button>
        </div>
    </div>
</div>

Código/GestorDocumentosEntrada/GestorDocumentosEntrada/Views/Menu/administratorMenu.cshtml
@{
    ViewBag.Title = "Menu Principal";
}

<div class="menu">
    <div class="row col-sm-8">
        <div class="col-sm-3">
            <img class="menuHeaderImage" src="@Url.Content("~/Content/Image/escudoSinFondo.png")">
        </div>
        <div class="col-sm-9">
            <h3 class="menuHeaderTitle">Menú Principal</h3>
        </div>
    </div>
    <div class="row col-sm-8">
        <div class="col-sm-12">
            <button type="button" class="menuButton" onClick="location.href='@Url.Action("UserList", "Administrator")'">Usuarios</button>
            <button type="button" class="menuButton" onClick="location.href='@Url.Action("procedureTypes", "Administrator")'">Tipo de Trámites</button>
            <button type="button" class="menuButton" onClick="location.href='@Url.Action("dailyProcedure", "Procedure")'">Recibir Documentos Diarios</button>
            <button type="button" class="menuButton" onClick="location.href='@Url.Action("displayProcedure", "Procedure")'">Vizualizar Trámite</button>
            <button type="button" class="menuButton" onClick="location.href='@Url.Action("Index", "LogIn")'">Salir</button>
        </div>
    </div>
</div>

Código/GestorDocumentosEntrada/GestorDocumentosEntrada/Views/Menu/platFormBossMenu.cshtml
@{
    ViewBag.Title = "Menu Principal";
}

<div class="menu">
    <div class="row col-sm-8">
        <div class="col-sm-3">
            <img class="menuHeaderImage" src="@Url.Content("~/Content/Image/escudoSinFondo.png")">
        </div>
        <div class="col-sm-9">
            <h3 class="menuHeaderTitle">Menú Principal</h3>
        </div>
    </div>
    <div class="row col-sm-8">
        <div class="col-sm-12">
            <button type="button" class="menuButton" onClick="location.href='@Url.Action("Create", "Procedure")'">Ingresar Trámite</button>
            <button type="button" class="menuButton" onClick="location.href='@Url.Action("Edit", "Procedure")'">Editar Trámite</button>
            <button type="button" class="menuButton" onClick="location.href='@Url.Action("Binnacle", "Reports")'">Generar Bitácora</button>
            <button type="button" class="menuButton" onClick="location.href='@Url.Action("Statistic", "Reports")'">Ver Estadísticas</button>
            <button type="button" class="menuButton"onClick="location.href='@Url.Action("Index", "LogIn")'">Salir</button>
        </div>
    </div>
</div>

Código/GestorDocumentosEntrada/GestorDocumentosEntrada/Views/Menu/platFormMenu.cshtml
@{
    ViewBag.Title = "Menu Principal";
}

<div class="menu">
    <div class="row col-sm-8">
        <div class="col-sm-3">
            <img class="menuHeaderImage" src="@Url.Content("~/Content/Image/escudoSinFondo.png")">
        </div>
        <div class="col-sm-9">
            <h3 class="menuHeaderTitle">Menú Principal</h3>
        </div>
    </div>
    <div class="row col-sm-8">
        <div class="col-sm-12">
            <button type="button" class="menuButton" onClick="location.href='@Url.Action("Create", "Procedure")'">Ingresar Trámite</button>
            <button type="button" class="menuButton" onClick="location.href='@Url.Action("SearchProcedure", "Procedure")'">Buscar Oficio</button>
            <button type="button" class="menuButton" onClick="location.href='@Url.Action("Statistic", "Reports")'">Ver Estadísticas</button>
            <button type="button" class="menuButton"onClick="location.href='@Url.Action("Index", "LogIn")'">Salir</button>
        </div>
    </div>
</div>